### ISSUE TITLE
Неверные моды

### ISSUE THREAD

**Issue by Andernisha** [kawaii-flesh/ModCD#8]
По какой-то причине программа видит Suika Game как Doom Eternal, а Vampire Survivors вообще 3 других игры
![Homebrew_Menu_20240926_235049_00](https://github.com/user-attachments/assets/f9370c39-648d-49c4-861f-97edce0bc9b0)

**Comment by Andernisha** [comment]
Забыл добавить лог на всякий
[log.txt](https://github.com/user-attachments/files/17153563/log.txt)

**Comment by kawaii-flesh** [comment]
Спасибо за репорт. Проверьте в DBI наличие битых игр. Их размер скорее всего будет 0 
Плз запустите приложенный билд и скиньте сюда log.txt после запуска
[buid.zip](https://github.com/user-attachments/files/17158506/buid.zip)

**Comment by Andernisha** [comment]
Из битых только Inscryption, но не думаю что он как-то влияет
Логи приложенного билда:
[log.txt](https://github.com/user-attachments/files/17163694/log.txt)

**Comment by kawaii-flesh** [comment]
Как раз дело в битой игре, удаление, с большей вероятностью, поможет. Если не сложно и у вас есть свободное время, чтобы помочь с отладкой, то плз напишите мне в ТГ: https://t.me/kawaii_flesh
