### ISSUE TITLE
Не запускається (ошибка доступа к репозиторию модов)

### ISSUE THREAD

**Issue by NVMarchuk** [kawaii-flesh/ModCD#9]
[log.txt](https://github.com/user-attachments/files/17156135/log.txt)

на третьому пункті установки завісає та через деякий час видає помилку

**Comment by NVMarchuk** [comment]
[log.txt](https://github.com/user-attachments/files/17156263/log.txt)

**Comment by kawaii-flesh** [comment]
Спасибо за репорт. Попробуйте заменить файл конфигурации `sd:/.modcd/config.json` на этот
[config.json](https://github.com/user-attachments/files/17158416/config.json)

**Comment by NVMarchuk** [comment]
сенкс, це вирішило проблему
